### ISSUE TITLE
how could I  communicate with you? Could you give me an email address?

### ISSUE THREAD

**Issue by huangzhenyu** [garysm/chatgpt-nba-api-plugin#2]
Hi, Garysm, I am a big fan for both NBA and chatgpt. I am going to develop an nba chat robot which have  three roles, including stats expert, commentator and real-time journalist . I am doing some langchain projects now and hope some parters together. Looking forward to your reply.

**Comment by garysm** [comment]
> Hi, Garysm, I am a big fan for both NBA and chatgpt. I am going to develop an nba chat robot which have three roles, including stats expert, commentator and real-time journalist . I am doing some langchain projects now and hope some parters together. Looking forward to your reply.

Hi there! I'd love to discuss a partnership.  You can send a message to me on my company's site [here](https://www.sabiasoftware.com/contact).
